/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    banners: Banner;
    'landing-pages': LandingPage;
    products: Product;
    events: Event;
    promotions: Promotion;
    coupons: Coupon;
    'blog-posts': BlogPost;
    'xp-levels': XpLevel;
    'fidelity-tags': FidelityTag;
    addresses: Address;
    orders: Order;
    'distributor-requests': DistributorRequest;
    'xp-transactions': XpTransaction;
    notifications: Notification;
    'inventory-movements': InventoryMovement;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      ordersHistory: 'orders';
      xpHistory: 'xp-transactions';
      distributorRequestsHistory: 'distributor-requests';
    };
    products: {
      inventoryHistory: 'inventory-movements';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'xp-levels': XpLevelsSelect<false> | XpLevelsSelect<true>;
    'fidelity-tags': FidelityTagsSelect<false> | FidelityTagsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'distributor-requests': DistributorRequestsSelect<false> | DistributorRequestsSelect<true>;
    'xp-transactions': XpTransactionsSelect<false> | XpTransactionsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'inventory-movements': InventoryMovementsSelect<false> | InventoryMovementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'manager' | 'content-editor' | 'authenticated-customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  phone?: string | null;
  cpf?: string | null;
  avatar?: (number | null) | Media;
  profileType: 'client' | 'partner' | 'distributor';
  distributorStatus?: ('none' | 'pending_review' | 'approved' | 'rejected') | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  fidelityTags?: (number | FidelityTag)[] | null;
  xpBalance?: number | null;
  level?: (number | null) | XpLevel;
  ordersHistory?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  xpHistory?: {
    docs?: (number | XpTransaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  distributorRequestsHistory?: {
    docs?: (number | DistributorRequest)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  benefitsUnlocked?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fidelity-tags".
 */
export interface FidelityTag {
  id: number;
  name: string;
  slug: string;
  applicableProfiles?: ('client' | 'partner' | 'distributor')[] | null;
  allowDistributorStacking?: boolean | null;
  benefits?:
    | {
        label: string;
        type?: ('percentage' | 'free-shipping' | 'priority-access' | 'gift') | null;
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "xp-levels".
 */
export interface XpLevel {
  id: number;
  level: number;
  name: string;
  minXP: number;
  benefits?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customer: number | Customer;
  code: string;
  status: 'pending' | 'awaiting-payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subtotal: number;
  profileDiscount?: number | null;
  fidelityDiscount?: number | null;
  promotionDiscount?: number | null;
  couponDiscount?: number | null;
  couponCode?: string | null;
  shippingAmount?: number | null;
  shippingAddress?: (number | null) | Address;
  total: number;
  paymentMethod?: ('credit-card' | 'pix') | null;
  paymentExternalId?: string | null;
  xpEarned?: number | null;
  trackingCode?: string | null;
  trackingUrl?: string | null;
  shippedAt?: string | null;
  deliveredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer: number | Customer;
  label?: string | null;
  recipientName: string;
  street: string;
  number: string;
  complement?: string | null;
  neighborhood: string;
  city: string;
  state: string;
  zipCode: string;
  isDefault?: boolean | null;
  latitude?: number | null;
  longitude?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "xp-transactions".
 */
export interface XpTransaction {
  id: number;
  customer: number | Customer;
  amount: number;
  source: 'order-paid' | 'event-ticket' | 'manual-adjustment';
  referenceId?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributor-requests".
 */
export interface DistributorRequest {
  id: number;
  customer: number | Customer;
  responsibleName: string;
  companyName: string;
  tradeName: string;
  cnpj: string;
  stateRegistration?: string | null;
  phone: string;
  commercialAddress: {
    street: string;
    number?: string | null;
    neighborhood?: string | null;
    city: string;
    state: string;
    zipCode: string;
  };
  website?: string | null;
  socialMedia?: string | null;
  observations?: string | null;
  documents?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  termsAccepted: boolean;
  status: 'pending_review' | 'approved' | 'rejected';
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  cta: {
    label: string;
    href: string;
  };
  image: number | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  slug: string;
  title: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  blocks?:
    | (
        | HeroBannerBlock
        | BenefitBarBlock
        | ProductCarouselBlock
        | CategoryGridBlock
        | EventHighlightBlock
        | TestimonialSectionBlock
        | RichContentSectionBlock
        | FAQSectionBlock
        | CTASectionBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBannerBlock".
 */
export interface HeroBannerBlock {
  eyebrow: string;
  title: string;
  subtitle: string;
  cta: {
    label: string;
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  image: number | Media;
  ambienceNotes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'HeroBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitBarBlock".
 */
export interface BenefitBarBlock {
  items?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'BenefitBar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductCarouselBlock".
 */
export interface ProductCarouselBlock {
  title: string;
  subtitle: string;
  collection?: ('featured' | 'kits' | 'all') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ProductCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock".
 */
export interface CategoryGridBlock {
  title: string;
  subtitle: string;
  items?:
    | {
        title: string;
        description: string;
        href: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CategoryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHighlightBlock".
 */
export interface EventHighlightBlock {
  title: string;
  subtitle: string;
  eventSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'EventHighlight';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialSectionBlock".
 */
export interface TestimonialSectionBlock {
  title: string;
  subtitle: string;
  testimonials?:
    | {
        name: string;
        role: string;
        quote: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TestimonialSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichContentSectionBlock".
 */
export interface RichContentSectionBlock {
  title: string;
  content?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'RichContentSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQSectionBlock".
 */
export interface FAQSectionBlock {
  title: string;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FAQSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTASectionBlock".
 */
export interface CTASectionBlock {
  title: string;
  subtitle: string;
  cta: {
    label: string;
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'CTASection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  category: string;
  featured?: boolean | null;
  isKit?: boolean | null;
  active?: boolean | null;
  variants?:
    | {
        name: string;
        sku: string;
        basePrice: number;
        partnerPrice?: number | null;
        distributorPrice?: number | null;
        stock: number;
        reorderLevel?: number | null;
        id?: string | null;
      }[]
    | null;
  inventoryHistory?: {
    docs?: (number | InventoryMovement)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-movements".
 */
export interface InventoryMovement {
  id: number;
  product?: (number | null) | Product;
  sku: string;
  type: 'sale' | 'return' | 'adjustment' | 'restock' | 'reservation' | 'reservation-cancel';
  quantity: number;
  previousStock?: number | null;
  newStock?: number | null;
  order?: (number | null) | Order;
  changedBy?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  summary: string;
  description: string;
  startsAt: string;
  endsAt: string;
  location: string;
  instructor: string;
  coverImage?: (number | null) | Media;
  batches?:
    | {
        name: string;
        price: number;
        quantity: number;
        sold?: number | null;
        status?: ('scheduled' | 'active' | 'sold-out') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  name: string;
  scope: 'product' | 'category' | 'order' | 'event';
  discountType: 'percentage' | 'fixed';
  value: number;
  startsAt: string;
  endsAt: string;
  active?: boolean | null;
  xpMultiplier?: number | null;
  eligibleProfiles?: ('client' | 'partner' | 'distributor')[] | null;
  eligibleTags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  discountType: 'percentage' | 'fixed';
  value: number;
  minPurchase?: number | null;
  startsAt: string;
  endsAt: string;
  active?: boolean | null;
  maxUses?: number | null;
  currentUses?: number | null;
  eligibleProfiles?: ('client' | 'partner' | 'distributor')[] | null;
  eligibleTags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  customer: number | Customer;
  type:
    | 'order-status'
    | 'promotion'
    | 'coupon'
    | 'xp-earned'
    | 'level-up'
    | 'distributor-approved'
    | 'distributor-rejected'
    | 'event-reminder'
    | 'system';
  title: string;
  message: string;
  href?: string | null;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'xp-levels';
        value: number | XpLevel;
      } | null)
    | ({
        relationTo: 'fidelity-tags';
        value: number | FidelityTag;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'distributor-requests';
        value: number | DistributorRequest;
      } | null)
    | ({
        relationTo: 'xp-transactions';
        value: number | XpTransaction;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'inventory-movements';
        value: number | InventoryMovement;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  cpf?: T;
  avatar?: T;
  profileType?: T;
  distributorStatus?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  fidelityTags?: T;
  xpBalance?: T;
  level?: T;
  ordersHistory?: T;
  xpHistory?: T;
  distributorRequestsHistory?: T;
  benefitsUnlocked?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  seoTitle?: T;
  seoDescription?: T;
  blocks?:
    | T
    | {
        HeroBanner?: T | HeroBannerBlockSelect<T>;
        BenefitBar?: T | BenefitBarBlockSelect<T>;
        ProductCarousel?: T | ProductCarouselBlockSelect<T>;
        CategoryGrid?: T | CategoryGridBlockSelect<T>;
        EventHighlight?: T | EventHighlightBlockSelect<T>;
        TestimonialSection?: T | TestimonialSectionBlockSelect<T>;
        RichContentSection?: T | RichContentSectionBlockSelect<T>;
        FAQSection?: T | FAQSectionBlockSelect<T>;
        CTASection?: T | CTASectionBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBannerBlock_select".
 */
export interface HeroBannerBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  image?: T;
  ambienceNotes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitBarBlock_select".
 */
export interface BenefitBarBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductCarouselBlock_select".
 */
export interface ProductCarouselBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  collection?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryGridBlock_select".
 */
export interface CategoryGridBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHighlightBlock_select".
 */
export interface EventHighlightBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  eventSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialSectionBlock_select".
 */
export interface TestimonialSectionBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  testimonials?:
    | T
    | {
        name?: T;
        role?: T;
        quote?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichContentSectionBlock_select".
 */
export interface RichContentSectionBlockSelect<T extends boolean = true> {
  title?: T;
  content?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQSectionBlock_select".
 */
export interface FAQSectionBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTASectionBlock_select".
 */
export interface CTASectionBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  category?: T;
  featured?: T;
  isKit?: T;
  active?: T;
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        basePrice?: T;
        partnerPrice?: T;
        distributorPrice?: T;
        stock?: T;
        reorderLevel?: T;
        id?: T;
      };
  inventoryHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  instructor?: T;
  coverImage?: T;
  batches?:
    | T
    | {
        name?: T;
        price?: T;
        quantity?: T;
        sold?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  scope?: T;
  discountType?: T;
  value?: T;
  startsAt?: T;
  endsAt?: T;
  active?: T;
  xpMultiplier?: T;
  eligibleProfiles?: T;
  eligibleTags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  value?: T;
  minPurchase?: T;
  startsAt?: T;
  endsAt?: T;
  active?: T;
  maxUses?: T;
  currentUses?: T;
  eligibleProfiles?: T;
  eligibleTags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  coverImage?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "xp-levels_select".
 */
export interface XpLevelsSelect<T extends boolean = true> {
  level?: T;
  name?: T;
  minXP?: T;
  benefits?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fidelity-tags_select".
 */
export interface FidelityTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  applicableProfiles?: T;
  allowDistributorStacking?: T;
  benefits?:
    | T
    | {
        label?: T;
        type?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  label?: T;
  recipientName?: T;
  street?: T;
  number?: T;
  complement?: T;
  neighborhood?: T;
  city?: T;
  state?: T;
  zipCode?: T;
  isDefault?: T;
  latitude?: T;
  longitude?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  code?: T;
  status?: T;
  items?: T;
  subtotal?: T;
  profileDiscount?: T;
  fidelityDiscount?: T;
  promotionDiscount?: T;
  couponDiscount?: T;
  couponCode?: T;
  shippingAmount?: T;
  shippingAddress?: T;
  total?: T;
  paymentMethod?: T;
  paymentExternalId?: T;
  xpEarned?: T;
  trackingCode?: T;
  trackingUrl?: T;
  shippedAt?: T;
  deliveredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributor-requests_select".
 */
export interface DistributorRequestsSelect<T extends boolean = true> {
  customer?: T;
  responsibleName?: T;
  companyName?: T;
  tradeName?: T;
  cnpj?: T;
  stateRegistration?: T;
  phone?: T;
  commercialAddress?:
    | T
    | {
        street?: T;
        number?: T;
        neighborhood?: T;
        city?: T;
        state?: T;
        zipCode?: T;
      };
  website?: T;
  socialMedia?: T;
  observations?: T;
  documents?:
    | T
    | {
        file?: T;
        id?: T;
      };
  termsAccepted?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "xp-transactions_select".
 */
export interface XpTransactionsSelect<T extends boolean = true> {
  customer?: T;
  amount?: T;
  source?: T;
  referenceId?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  customer?: T;
  type?: T;
  title?: T;
  message?: T;
  href?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-movements_select".
 */
export interface InventoryMovementsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  type?: T;
  quantity?: T;
  previousStock?: T;
  newStock?: T;
  order?: T;
  changedBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}